export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PROFILE: '/profile',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_TOPPINGS: '/admin/toppings',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_PROMOTIONS: '/admin/promotions',
  ADMIN_USERS: '/admin/users',
  ADMIN_STATS: '/admin/stats',
}
